name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: wasm-pack-action
      uses: jetli/wasm-pack-action@v0.4.0      
    - name: Build
      run: wasm-pack build wasm-lib --verbose
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0
        cache: 'yarn'
        registry-url: 'https://registry.npmjs.org'
    - run: yarn install --immutable
    - name: Build the CLI
      run: yarn build

